### ISSUE TITLE
Rendering a pdf at a specific page

### ISSUE THREAD

**Issue by hamdi3** [lfoppiano/streamlit-pdf-viewer#61]
While there's a parameter for rendering specific pages, I was wondering if it would be possible to add the possibility to view the pdf starting at a specific page.
I'm thinking of something like this for example:
```
    page_param = f"#page={page_number}"
    pdf_display = (
        f'<iframe src="data:application/pdf;base64,{base64_pdf}{page_param}" '
        'width="100%" height="600" type="application/pdf"></iframe>'
    )
    streamlit.markdown(pdf_display, unsafe_allow_html=True)
```

**Comment by lfoppiano** [comment]
Hi @hamdi3, do you mean to scroll down to a specific page? There is an issue for that  #24, and someone asked also the ability to scroll down to a specific coordinate / annotations #55 

I have an idea on how to implement it, I'll check this after I've solved the issue with Chrome #60 🙂

**Comment by hamdi3** [comment]
@lfoppiano That's exactly what i mean, thanks in advance :)

**Comment by lfoppiano** [comment]
I've released the first dev version implementing this feature. If you specify either `scroll_to_page` or `scroll_to_annotation` when calling `pdf_viewer()`, it will scroll to the desired page or annotation. The options are exclusive. Documentation is [here](https://github.com/lfoppiano/streamlit-pdf-viewer/tree/scroll-to-html-id?tab=readme-ov-file#params). 

Please test it and let me know what you think, it might require more iterations because streamlit is reloading the pages, so maybe we need to think of a solution using `@st.fragment`.

**Comment by hamdi3** [comment]
@lfoppiano  First of all thanks for the good work!

I've tested multiple things and it worked just fine. It also worked in diffrent tabs without an issue! Only thing that would be important for the tool generally imo is to fix the render_text to work in chrome. beside that I can't find anything to complain about. You guys did a great job!

**Comment by lfoppiano** [comment]
Thanks @hamdi3. I had to work on this issue before because it's needed in a project I'm working, the Chrome issue, will be definitely the next issue I will focus on.
